services:
  real-fake-job-detection-api:
    image: public.ecr.aws/j4r9x7x2/rishabhpancholi/real-fake-job-detection-api:latest
    container_name: real-fake-job-detection-api
    ports:
      - "8000:8000"
    env_file:
      - .env
